export const data = {
  POSTS: [
    {
      _id: "1",
      text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
      image:
        "https://images.hdqwalls.com/download/last-talk-before-going-to-school-rx-1366x768.jpg",
      user: {
        username: "johndoe",
        image: "/avatars/boy1.png",
        fullname: "John Doe",
      },
      comments: [
        {
          _id: "1",
          text: "Nice Tutorial",
          user: {
            username: "janedoe",
            image: "/avatars/girl1.png",
            fullname: "Jane Doe",
          },
        },
      ],
      likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
    },
    {
      _id: "2",
      text: "How you guys doing? 😊",
      user: {
        username: "johndoe",
        image: "/avatars/boy2.png",
        fullname: "John Doe",
      },
      comments: [
        {
          _id: "1",
          text: "Nice Tutorial",
          user: {
            username: "janedoe",
            image: "/avatars/girl2.png",
            fullname: "Jane Doe",
          },
        },
      ],
      likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
    },
    {
      _id: "3",
      text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
      image:
        "https://images.hdqwalls.com/download/the-silent-avenger-fc-1366x768.jpg",
      user: {
        username: "johndoe",
        image: "/avatars/boy3.png",
        fullname: "John Doe",
      },
      comments: [],
      likes: [
        "6658s891",
        "6658s892",
        "6658s893",
        "6658s894",
        "6658s895",
        "6658s896",
      ],
    },
    {
      _id: "4",
      text: "I'm learning GO this week. Any tips? 🤔",
      image:
        "https://images.hdqwalls.com/download/boat-minimal-lake-hy-1366x768.jpg",
      user: {
        username: "johndoe",
        image: "/avatars/boy3.png",
        fullname: "John Doe",
      },
      comments: [
        {
          _id: "1",
          text: "Nice Tutorial",
          user: {
            username: "janedoe",
            image: "/avatars/girl3.png",
            fullname: "Jane Doe",
          },
        },
      ],
      likes: [
        "6658s891",
        "6658s892",
        "6658s893",
        "6658s894",
        "6658s895",
        "6658s896",
        "6658s897",
        "6658s898",
        "6658s899",
      ],
    },
  ],
  USERS_FOR_RIGHT_PANEL: [
    {
      _id: "1",
      fullname: "John Doe",
      username: "johndoe",
      image: "/prof.jpeg",
    },
    {
      _id: "2",
      fullname: "Jane Doe",
      username: "janedoe",
      image: "/prof.jpeg",
    },
    {
      _id: "3",
      fullname: "Bob Doe",
      username: "bobdoe",
      image: "/prof.jpeg",
    },
    {
      _id: "4",
      fullname: "Daisy Doe",
      username: "daisydoe",
      image: "/prof.jpeg",
    },
  ],
};

export const notifications = [
  {
    _id: "1",
    from: {
      _id: "1",
      username: "johndoe",
      profileImg: "/images/profile1.png",
    },
    type: "follow",
  },
  {
    _id: "2",
    from: {
      _id: "2",
      username: "janedoe",
      profileImg: "/images/profile2.png",
    },
    type: "like",
  },
  {
    _id: "3",
    from: {
      _id: "3",
      username: "alexsmith",
      profileImg: "/images/profile3.png",
    },
    type: "follow",
  },
  {
    _id: "4",
    from: {
      _id: "4",
      username: "emilywhite",
      profileImg: "/images/profile4.png",
    },
    type: "like",
  },
];
